#! /usr/bin/env bash

if ! touch /data/.verify_access; then
  echo "ERROR: /data doesn't seem to be writable. Please make sure attached directory is writable by uid=${UID} "
  exit 2
else
  rm /data/.verify_access || true
fi


# Optional disable GUI for headless servers
if [[ ${GUI} = false || ${GUI} = FALSE ]]; then
  EXTRA_ARGS="${EXTRA_ARGS} nogui"
fi


# put these prior JVM_OPTS at the end to give any memory settings there higher precedence
echo "Setting initial memory to ${INIT_MEMORY:-${MEMORY}} and max to ${MAX_MEMORY:-${MEMORY}}"
JVM_OPTS="-Xms${INIT_MEMORY:-${MEMORY}} -Xmx${MAX_MEMORY:-${MEMORY}} ${JVM_OPTS}"

echo "Starting $SERVER_JAR with command:"
echo "mc-server-runner java $JVM_XX_OPTS $JVM_OPTS -jar $SERVER_JAR $@ $EXTRA_ARGS"
echo "Using Java version $(java -version)"
exec mc-server-runner java $JVM_XX_OPTS $JVM_OPTS -jar $SERVER_JAR "$@" $EXTRA_ARGS
